services:
  backend:
    build:
      context: ./holiday-source
      dockerfile: Dockerfile
    ports:
      - "5254:5254"
    volumes:
      - ./holiday-source:/app
  frontend:
    build: 
      context: ./holidays-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./holidays-react:/usr/src/app
